### ISSUE TITLE
Failed searches on Geneious 9.1.7

### ISSUE THREAD

**Issue by vladimirvig** [Biomatters/geneious-eupathdb#1]
Error message below:
Search failed - The EuPathDB server responded with an error message:  User Error (#020): Some of the input parameters are invalid or missing.

Cause: The EuPathDB server responded with an error message:  User Error (#020): Some of the input parameters are invalid or missing. com.biomatters.geneious.publicapi.databaseservice.DatabaseServiceException at com.biomatters.plugins.eupathdb.database.EukaryoticDatabase.getException(EukaryoticDatabase.java:406) at com.biomatters.plugins.eupathdb.database.EukaryoticDatabase.getResponseFromWebService(EukaryoticDatabase.java:388) at com.biomatters.plugins.eupathdb.database.EukaryoticDatabase.search(EukaryoticDatabase.java:234) at com.biomatters.plugins.eupathdb.services.EuPathDatabaseService.retrieve(EuPathDatabaseService.java:102) at com.biomatters.iseek.databasepanel.p.a(DatabaseServiceDocumentList.java:311) at com.biomatters.iseek.databasepanel.ae.a(DatabaseServiceModel.java:112) at et.run(Task.java:86) at java.lang.Thread.run(Thread.java:745)

**Comment by matthew-cheung** [comment]
Hi there,

Thanks for reporting this.  This looks like the EuPath DB API we use has changed.  Will try to get a fix out for this sometime in the new year.

**Comment by frankbiomatters** [comment]
Hi vladimirvig,

I have fixed this issue, and the latest release v1.0.1 includes my fix, you can download and try, thanks.

**Comment by vladimirvig** [comment]
Hi, frankbiomatters,
I downloaded the release and got the following Geneious error on an install attempt:
Failed to load plugin com.biomatters.plugins.eupathdb.EuPathDBPlugin: This plugin is written for a newer version of Geneious. It will not work with this version.
(plugin.getMinimumApiVersion()=4.1000 and current Geneious API version =4.918)

I am running Geneious 9.1.8 (just updated to this maintenance release).

**Comment by frankbiomatters** [comment]
hi vladimirvig,
I have fixed this problem in release v1.0.2, please download and try again, thanks.

**Comment by vladimirvig** [comment]
Appears to be fixed. Thank you!
